# Portfolio site configuration
minimal_mistakes_skin: "plum"

locale: "ko-KR"
title: "Joohyeng's Portfolio"
title_separator: "|"
name: "Joohyeng"
description: "Backend Developer Portfolio"
url: "https://joohyeng.github.io"
baseurl: ""
repository: "Joohyeng/Joohyeng.github.io"

masthead_title:
words_per_minute: 200
search: false

comments:
  provider: false

social:
  type: Person
  name: "Joohyeng"
  links:
    - "https://github.com/Joohyeng"

author:
  name: "Joohyeng"
  avatar:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Joohyeng"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Joohyeng"

include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_date: true
      comments: false
      related: false
